image:
  file: .gitpod.Dockerfile

tasks:
  - init: psql -f database-setup.sql
    command: 
      python -m pip install Django
      pip install psycopg2-binary
      python manage.py migrate
      
ports:
  - port: 8000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
  - port : 3000
    onOpen: notify