image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      psql -f database-setup.sql
      pip install --upgrade pip wheel setuptools
      pip install Django
      pip install psycopg2-binary
      python manage.py migrate
  - command: |
      python manage.py runserver  

      
ports:
  - port: 8000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
  - port : 3000
    onOpen: notify